### ISSUE TITLE
Feature Request: Add optional relationships that line up with the ODM

### ISSUE THREAD

**Issue by scottpas** [CybercentreCanada/assemblyline-service-virustotal-static#8]
Create submission parameters for the service to optionally add relationships available from the VT API, that line up with the ODM. Ideally, this parameter could be a comma-separated list of relationships that someone would like to obtain, since this would be identical to how VT's API works.
For example:
```
https://www.virustotal.com/api/v3/file/{file_hash}?relationships=contacted_ips,contacted_domains,contacted_urls,behaviours
```
(modified query from the documentation: https://developers.virustotal.com/reference/relationships)

A full list of file relationships can be found here
https://developers.virustotal.com/reference/files#relationships

Another nice-to-have feature: add "download_evtx" and "download_pcap" flags, which would grab any EVTX/PCAP files from related sandbox submissions, which could be then scanned against Sigma signatures in AL.
There are details on "has_evtx" and "has_pcap" values here: 
https://developers.virustotal.com/reference/file-behaviour-summary#object-attributes

**Comment by cccs-rs** [comment]
See for more details: https://discord.com/channels/908084610158714900/908717441771794472/1001131589641707611

Re-open if necessary.
